### ISSUE TITLE
Command `open` not found on Linux

### ISSUE THREAD

**Issue by h4ckitt** [tmonfre/zoom-cli#1]
I Installed This Program And Tried Running It But I Kept Getting Error
```
sh: 1: open: not found
```

After A Little Digging I Found Out That Command `open` Has Been Replaced With `xdg-open` On My Distro.

And After Modifying The Necessary Place In The Code, And Rebuilt, It Started Working.

I Thought To Put That Here, Since You Might Want To Account For It And Save Some Unsuspecting Users The Headache.

**Comment by tmonfre** [comment]
Thanks for reporting. I'll look into checking for `open` vs `xdg-open` before running the command.

**Comment by tmonfre** [comment]
@h4ckitt fixed and published a new release (v1.1.4). `brew upgrade zoom` should fix for you. Thanks again for reporting

**Comment by h4ckitt** [comment]
Thank You Very Much.
