### ISSUE TITLE
Link Shared Libraries Into Executable.

### ISSUE THREAD

**Issue by h4ckitt** [tmonfre/zoom-cli#3]
Hi, Sorry For The Bother,

Is It Possible To Link The Shared Libraries Into The Executable Such That The Executable Can Work As A Standalone Anywhere.

Thanks.

**Comment by tmonfre** [comment]
@h4ckitt I actually originally had it setup that way, but the package I'm using to bundle the app ([PyInstaller](https://github.com/pyinstaller/pyinstaller)) has to unpack all the dependencies into a temporary directory every time the command is run, so it ends up being pretty slow.

See https://stackoverflow.com/questions/9469932/app-created-with-pyinstaller-has-a-slow-startup for more info.

**Comment by tmonfre** [comment]
I can add a flag to the `build.sh` script to compile as one executable if you would like. That way it's an option for you to use when building locally. I will continue to bundle it as the directory for better run time, so the published package will exist that way.

Let me know if you'd like me to create that flag. Note that bundling it into one file is just a matter of adding `--onefile` at the end of this line: https://github.com/tmonfre/zoom-cli/blob/88bf548bf156682cdeaa0c826d768e486bd35143/build.sh#L2

**Comment by h4ckitt** [comment]
I'll Save You The Stress Of Adding It And Everyone Else Of The Slow Build Since I'm The Only One Requesting The Feature.

I Don't Mind Slow Build As My Use Case Is A Crazy One That Would Benefit Immensely From The `--onefile` Option.

Thank You Very Much, Keep Up The Awesome Work.

**Comment by tmonfre** [comment]
Sounds good. I'm curious what you are building? I'd be happy to create more features that might benefit your project. Let me know.
