### ISSUE TITLE
Won't autofill passwords

### ISSUE THREAD

**Issue by tomginsberg** [tmonfre/zoom-cli#6]
With the newest version passwords are not auto filled. Per [this stack exchange post](https://superuser.com/questions/1563255/start-a-zoom-meeting-from-the-command-line) I believe you can fix it by changing "?pwd=" to "&pwd=" in `launch_zoommtg_url`

Example:

```
zoom save -n [name] --id [id] -p [pwd]
zoom name
```
Starts zoom and tried to join but does not fill in the password. Same issue if I use `--url` and `-p` arguments

When I manually run 
```
open "zoommtg://zoom.us/join?action=join&confno=<id>?pwd=<pwd>" 
```
I get the same behaviour, but changing `?` to `&` the meeting will launch

**Comment by tmonfre** [comment]
Can you provide what command you are running to save? Interim fix would be to include password in meeting url when saving.

**Comment by tomginsberg** [comment]
Including the password in either the & or ? format doesn't seem to help

**Comment by tmonfre** [comment]
Hmm I know that zoom hashes the passwords in the URL format for security reasons. Do you have a single zoom link with the hashed password in it, rather than the separate password?

**Comment by tomginsberg** [comment]
Yes I have one, I tired using `zoom save -n test --url [URL with hashed pwd]`  when I ran `zoom test` nothing happens and no error is thrown

**Comment by tmonfre** [comment]
@tomginsberg can you try updating to `v1.1.6` and see if it works for you? If homebrew is giving you the sha256 mismatch again, untap the cask and re-tap. I found that should do the trick.

**Comment by tomginsberg** [comment]
great it works!

**Comment by tmonfre** [comment]
Nice! Will close this then.
